spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
    discovery:
      enabled: true
  logging:
    level:
      org.springframework.cloud.gateway: TRACE
      org.springframework.cloud.gateway.route.RouteDefinitionLocator: TRACE
      org.springframework.web.reactive.DispatcherHandler: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka