server:
  port: 8087

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


aws:
  s3:
    accessKeyId: AKIAXZMEDYBZKSGKGMJ6
    secretAccessKey: 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
    bucket: happypathbucket123
    region: us-east-2