server:
  port: 8087

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


aws:
  s3:
    bucket: happypathbucket123
    region: us-east-2
    access-key: AKIAXZMEDYBZKSGKGMJ6
    secret-key: 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
