spring:
  application:
    name: email-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 383fc5589c9b2b
    password: 592ce283aa55c4
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  # Enabling STARTTLS (this is for encryption)
          ssl:
            enable: false  # Disable SSL, since STARTTLS is being used instead

server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

queue:
  name: email-queue
  exchange: email-exchange
  routing-key: email-routing-key