spring:
  application:
    name: post-reply-service

  data:
    mongodb:
      uri: mongodb+srv://zhengh1005:273732390@cluster1.e5kwehs.mongodb.net/tempDB?retryWrites=true&w=majority&appName=Cluster1

  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8085
  error:
    include-message: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.postreplyservice: DEBUG
