#spring:
#  application:
#    name: post-reply-service
#  config:
#    import: "configserver:"
#  cloud:
#    config:
#      uri: http://localhost:8888
spring:
  application:
    name: post-reply-service
  config:
    import: "configserver:http://localhost:8888"
