spring:
  application:
    name: api-gateway
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      reactor.netty: DEBUG

  config:
    import: configserver:http://localhost:8888/
