spring:
  application:
    name: api-gateway
  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      org.springframework.boot.autoconfigure.security: DEBUG

  config:
    import: configserver:http://localhost:8888/
