spring:
  application:
    name: history-service
  config:
    import: "configserver:http://localhost:8888"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, beans, env, httptrace
  endpoint:
    health:
      show-details: always
