spring:
  application:
    name: user-service
  config:
    import: configserver:http://localhost:8888
  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      org.springframework.boot.autoconfigure.security: DEBUG


