server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /Users/fan/IdeaProjects/forum-team_project/config-repo
#          file:../config-repo

          # /Users/crystalzhao95/react-tabs-hw/forum-project/config-repo