server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:

          search-locations: file:C:\Users\LSY20\IdeaProjects\forum-project-5.8\config-repo
          #/Users/27373/github/forum-project/config-repo

          # C:\Users\silas\IdeaProjects\forum-project\config-repo
          #  ..\config-repo
          # /Users/crystalzhao95/react-tabs-hw/forum-project/config-repo
          #/Users/27373/github/forum-project/config-repo

