server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /Users/27373/github/forum-project/config-repo

          # /Users/crystalzhao95/react-tabs-hw/forum-project/config-repo